replicaCount: 1

image:
  repository: cloudketan/node-project
  tag: "v1-dev"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007

containerPort: 3000

env:
  ENVIRONMENT: dev
  PORT: "3000"

resources: {}

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false

podLabels: {}
podAnnotations: {}

# Fix ServiceAccount template
serviceAccount:
  create: true
  name: ""

# Fix httproute template
httpRoute:
  enabled: false
